use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/LNOrganization/LNSpec.git'
platform :ios, '9.0'


target 'LNAccountModule_Example' do
  pod 'LNAccountModule', :path => '../'
#  pod 'LNCommonKit', :path => '../../LNCommonKit'
#  pod 'LNModuleProtocol', :path => '../../LNModuleProtocol'
  target 'LNAccountModule_Tests' do
    inherit! :search_paths
  end
end
