use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/NoNameOrganazation/LNSpec.git'
platform :ios, '9.0'


target 'LNAccountModule_Example' do
  pod 'LNAccountModule', :path => '../'
  target 'LNAccountModule_Tests' do
    inherit! :search_paths

    
  end
end
